In [2]:
# ============================================
# NumPy Refresher — ML Tooling (Week 2)
# ============================================

import numpy as np

## 1. Random Seed for Reproducibility

In [3]:
np.random.seed(42)
print("\n🔹 Random seed set to 42")


🔹 Random seed set to 42


## 2. Scalars, Vectors, Matrices, Tensors

In [4]:
scalar = np.array(5)
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("\nScalar:", scalar)
print("Vector:\n", vector)
print("Matrix:\n", matrix)
print("Tensor:\n", tensor)
print("Matrix shape:", matrix.shape, " | Tensor shape:", tensor.shape)


Scalar: 5
Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Matrix shape: (2, 3)  | Tensor shape: (2, 2, 2)


## 3. Creating Arrays

In [5]:
print("\nZeros:\n", np.zeros((2, 3)))
print("\nOnes:\n", np.ones((3, 2)))
print("\nArange:\n", np.arange(0, 10, 2))
print("\nLinspace:\n", np.linspace(0, 1, 5))


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Arange:
 [0 2 4 6 8]

Linspace:
 [0.   0.25 0.5  0.75 1.  ]


## 4. Indexing & Slicing

In [6]:
x = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print("\nElement [0,2]:", x[0, 2])
print("Element [-1,0]:", x[-1, 0])

print("\nSlice [0:2, 1:]:\n", x[0:2, 1:])  # first 2 rows, last 2 cols


Element [0,2]: 30
Element [-1,0]: 70

Slice [0:2, 1:]:
 [[20 30]
 [50 60]]


## 5. Arithmetic Operations

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\na + b =", a + b)
print("a * b =", a * b)
print("a ** 2 =", a ** 2)


a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]


## 6. Dot Product

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print("\nDot Product:\n", np.dot(A, B))

## 7. Axis Operations

In [8]:
print("\nSum down columns (axis=0):", x.sum(axis=0))
print("Sum across rows (axis=1):", x.sum(axis=1))


Sum down columns (axis=0): [120 150 180]
Sum across rows (axis=1): [ 60 150 240]


## 8. Broadcasting

In [9]:
y = np.array([1, 2, 3])
print("\nBroadcast multiply y*2:", y * 2)
print("Broadcast add matrix + 10:\n", x + 10)


Broadcast multiply y*2: [2 4 6]
Broadcast add matrix + 10:
 [[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


## 9. Transpose

In [ ]:
print("\nTranspose of A:\n", A.T)

## 10. Reshape

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("\nReshape to (2,3):\n", arr.reshape(2, 3))
print("Reshape with -1:\n", arr.reshape(-1, 1))


Reshape to (2,3):
 [[1 2 3]
 [4 5 6]]
Reshape with -1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## 11. Concatenation

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

print("\nConcatenate along axis=0 (add rows):\n", np.concatenate((a, b), axis=0))
print("\nConcatenate along axis=1 (add cols):\n", np.concatenate((a, b.T), axis=1))

## 12. Expanding / Reducing Dimensions

In [ ]:
z = np.array([1, 2, 3])
print("\nOriginal shape:", z.shape)
z_expanded = np.expand_dims(z, axis=0)
print("After expand_dims(axis=0):", z_expanded.shape)
z_squeezed = np.squeeze(z_expanded)
print("After squeeze():", z_squeezed.shape)

## 13. Randomness & Reproducibility

In [ ]:
print("\nRandom numbers (same every run):\n", np.random.rand(2, 3))

In [14]:
import pandas as pd

In [16]:
df = pd.read_csv('Titanic-Dataset.csv')

df.describe() 

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200